# /timecard/config.ini
wifi_ssid=PSS_Office
wifi_pass=P550ffice$

mqtt_host=10.0.0.180
mqtt_port=1883
mqtt_user=timecard
mqtt_pass=letmein

site=carrwood
stream=timecard
actor=timecard
device_name=carr-tc-02 # Unique ID < 24 chrs
birthday=20250910 # Change when put in use
